version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "dev_db"
      POSTGRES_USER: "dev_user"
      POSTGRES_PASSWORD: "dev_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - dev-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dev-data: